name: Test

on:
  workflow_dispatch:
  push:
    branches:
      -master
      -development
      -rileym666-patch-1

jobs:
  python_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
        python-version: [3.6.2, 3.7, 3.8, 3.9]


    steps:
      - uses: actions/checkout@v2
      - name: Python setup
        uses: actions/setup-python@v2
      - name: Add requirements
        run: |
          python -m pip install --upgrade pip
          pip install coverage
          pip install unittest
          with:
            python-version: ${{ matrix.python-version }}
      - name: run unit tests
        run: |
          coverage run -m unittest discover
