# This workflow will attempt to build a Python Package using pip to test if it is buildable

name: Test Build

on:
  push:
    branches:
      - master
      - rileym666-patch-1
  release:
    types: [published]

jobs:
  ci:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.6]

    steps:
      - uses: actions/checkout@v2
      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: run unit tests
        run: |
          python -m tests.test_pdfreader_init
          python -m tests.test_pdfstring
          python -m tests.test_pdfdict
          python -m tests.test_roundtrip
