name: Test

on:
  push:
    branches:
      - master
      - development
      - "rileym666-patch-1"

jobs:
  python_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-20.04, windows-latest]
        python-version: [3.6.2]


    steps:
      - uses: actions/checkout@v2
      - name: Python setup
        uses: actions/setup-python@v2
      - name: Add requirements
        run: |
          python -m pip install --upgrade pip
          pip install coverage

      - name: run unit tests
        run: |
          coverage run -m unittest discover
